[package]
name = "neohook"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
windows.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
retour = "0.3"
zmq = "0.10"
regex = "1.10"
lazy_static = "1.4"